### PR TITLE
split l3build.lua into many separate files

### PR DESCRIPTION
**Pull request by wspr**
see #35

no big philosophy behind the files chosen -- some may need to be divided further, others re-combined

removed some (but not all) "local" versions of function names here and there; not sure what our guiding approach should be overall

I've done some degree of testing that I've caught all the "scope" issues, although I can't claim 100% coverage

### CODE REVIEW

**Comment by josephwright** [comment]
On the local versions business, my understanding is that Lua best practice is to always make local copies of standard stuff. For example, if you look at the ConTeXt sources they have things like
```lua
local print = print
local pairs = pairs
local sort  = table.sort
```
I can see that this makes copying code from one place to another 'interesting' (in the above, for the `sort` case but not the other two, of course).

**Comment by josephwright** [comment]
I'm happy for this to get merged: it would be good to do it before dealing with any other issues ...

**Comment by wspr** [comment]
Well, here goes nothing... do feel free to re-add `local` definitions of functions as you see fit! I'm not too fussed either way, but I have to admit I find it makes code harder to not have the function "prefix". OTOH if that's not best practice then so be it :)

**Comment by josephwright** [comment]
@wspr We can stick with just using the global names: I'm not that fussed. (I have to admit that I find the local names a bit strange too: I have a feeling it's because I'm used to TeX.)

**Comment by FrankMittelbach** [comment]
@wspr @josephwright  as I understand it this local x = x or local y = foo.y is really there for efficiency it is much faster for lua to look up a local name rather than one in its global name space and you gain a quite noticable amount of speed. However, the execution time of those scripts depend much more on the number of external (TeX) tests and the time spend there than on spending time in the actual lua code. It is therefore most likely of minor importance for us.

**Comment by blefloch** [comment]
> those scripts depend much more on the number of external (TeX) tests and
> the time spend there than on spending time in the actual lua code.
Most agreed; the only exception is code that's applied to every test
file (even more so for code that's applied to every line).  Presumably
all functions there should be copied locally?

**Comment by FrankMittelbach** [comment]
agreed, basically with this best practice you can gain 10% or more in speed. All I'm saying if 90% of the time spend is spend not in lua code that ends up being 1-2% in the end. On the other hand, getting into the habit of doing it always may not be a bad idea

**Pull request merged**
