### PR TITLE
Add MiKTeX check

### PR DESCRIPTION
**Pull request by koppor**
To enable working on https://github.com/latex3/l3build/issues/303, this PR adds MiKTeX as separated check.

Output with the check:

```
Run texlua l3build.lua ctan -H --show-log-on-error
Running l3build with target "check" for module "."
Running l3build with target "check" and configuration "build"
./l3build-unpack.lua:87: attempt to index a nil value
```

Hope, this will make it easier to work on a fix.

### CODE REVIEW

**Comment by josephwright** [comment]
I'm a bit worried about running a MiKTeX check on anything other than Windows: seems rather odd to me! (Yes, I know that CS has extended MiKTeX to other platforms, but Windows is the place it really used.)

**Comment by koppor** [comment]
It appears "strange" to me too. I see, however, that the debian packages are kept being updated on CTAN: https://ctan.net/systems/win32/miktex/setup/deb/dists/

image

Since there are many Windows users out there - an automatic check would be beneficial.

I got two proposals to proceed. Just let me know.

Proposal A (more work for me):

Port this PR to Windows. Meaning: Use the GitHub action Windows runner, install MiKTeX for Windows and let the thing run on Windows.

Proposal B (more risk for you):

- Fix https://github.com/latex3/l3build/issues/303
- Merge that fix into this branch
- Check if branch runs through
- Merge the branch into `main`
- In case the CI works broken l3build, but MiKTeX on Windows does not, remove this check and implement proposal A.

**Comment by josephwright** [comment]
I think before we tackle either route we need to see if MiKTeX is workable: like I've said in #303, there is an issue with allowable rounding differences.

**Comment by koppor** [comment]
Then, I close this, because it will take longer time.

The "allowable rounding differences" will be a hard issue. Maybe, testing with l3build will be recommended on TeXLive only.

**Comment by josephwright** [comment]
@koppor I'll see what I get back from Christian: that's a blocker for us on MiKTeX, unfortunately.

**Pull request closed without merging**
