### PR TITLE
Better handle spaces in file and path names

### PR DESCRIPTION
**Pull request by zauguin**

### CODE REVIEW

**Comment by josephwright** [comment]
Seems to miss `l3build-unpack`, and then life gets ... interesting

**Comment by zauguin** [comment]
@josephwright Should be fixed now. Previously I only looked for commands called with `os.execute` and therefore missed the two files using `io.popen`.

**Comment by josephwright** [comment]
Now `unpack`, `install`, `check` all work, but `doc` (and thus `ctan`) fail.

**Comment by josephwright** [comment]
@zauguin  Do you think we can get this working or should we close the PR?

**Comment by josephwright** [comment]
@zauguin I'm minded to close here ATM as we are not sure about this - thoguhts?

**Pull request closed without merging**
